package com.github.shuntak.generator.example.hello.entity;

import lombok.*;

import javax.annotation.Generated;
import javax.persistence.*;
import javax.validation.constraints.*;
import java.io.Serializable;
import java.time.ZonedDateTime;

/**
 * Card entity base class.
 * Auto generated by JPA code generator.
 */
@Generated(value = "JPACodeGenerator")
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@ToString
@EqualsAndHashCode
@MappedSuperclass
public abstract class AbstractCard implements Serializable {
    @Id
    @Column(name = "id")
    @NotNull
    private Integer id;

    @Column(name = "name")
    @NotNull
    @Size(max = 255)
    private String name;

    @Column(name = "rarity")
    @NotNull
    private Integer rarity;

    @Column(name = "is_available")
    private boolean isAvailable;

}
