package com.github.shuntak.generator.example.hello.entity;

import lombok.*;
import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

import javax.persistence.*;
import javax.validation.constraints.*;
import java.io.Serializable;
import java.time.ZonedDateTime;

/**
 * Card entity base class.
 * Auto generated by JPA code generator.
 */
@javax.annotation.Generated(value = "JPACodeGenerator")
@NoArgsConstructor
@AllArgsConstructor
@Data
@MappedSuperclass
public abstract class AbstractCard implements Serializable {
    @Id
    @Column(name = "id")
    @NotNull
    private Integer id;

    @Column(name = "name")
    @NotNull
    @Size(max = 255)
    private String name;

    @Column(name = "rarity")
    @NotNull
    private Integer rarity;

    @Column(name = "is_available")
    private boolean isAvailable;

}
