package com.github.shuntak.generator.example.hello.entity.dao;

import java.util.Optional;
import javax.annotation.Generated;
import javax.persistence.EntityManager;

/** Abstract DAO interface. Auto generated by JPA code generator.*/
@Generated(value = "JPACodeGenerator")
public interface AbstractDao<E> {
  Class<E> getEntityClass();

  EntityManager getEntityManager();

  E persist(E entity);

  E merge(E entity);

  E remove(E entity);

  Optional<E> find(Object pk);
}
