package com.github.shuntak.generator.example.hello.entity.dao;

import com.github.shuntak.generator.example.hello.entity.AbstractCard;
import com.github.shuntak.generator.example.hello.entity.ext.Card;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.Optional;

/**
 * Card DAO base interface.
 * Auto generated by JPA code generator.
 */
@javax.annotation.Generated(value = "JPACodeGenerator")
public interface AbstractCardDao extends AbstractDao<Card> {
    Card create(Card card);

    Card create(Integer id, String name, Integer rarity);

    List<Card> findAll();

    Optional<Card> find(Integer id);
}
