package com.github.shuntak.generator.example.hello.entity.dao;

import com.github.shuntak.generator.example.hello.entity.ext.User;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.Optional;

/**
 * User DAO base interface.
 * Auto generated by JPA code generator.
 */
@javax.annotation.Generated(value = "JPACodeGenerator")
public interface AbstractUserDao extends AbstractDao<User> {
    User create(User user);

    User create(String name);

    List<User> findAll();

    Optional<User> find(Long id);
}
