package com.github.shuntak.generator.example.hello.entity.dao;

/**
 * Abstract DAO interface.
 * Auto generated by JPA code generator.
 */
@javax.annotation.Generated(value = "JPACodeGenerator")
public interface AbstractDao<E> {
}
